### PR TITLE
Create zoom_guidelines.md

### PR DESCRIPTION
**Pull request by jmertic**
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by jmertic** [comment]
@dheckenberg Another one to add to the next TAC meeting ;-)

**Comment by jmertic** [comment]
Depends on https://github.com/AcademySoftwareFoundation/tac/pull/150

**Comment by lgritz** [comment]
Thanks. Clear, and I learned a few things.

**Comment by jfpanisset** [comment]
Looks good, one suggestion as a "pro tip": all attendees not joining via phone should make sure their name and affiliation (if any) are correctly represented in the attendee list for the meeting.

**Comment by dheckenberg** [comment]
Added to agenda.  Thanks @jmertic

**Comment by jmertic** [comment]
@jfpanisset great suggestion! Added a line in there now - let me know if that hits the mark.

**Comment by jfpanisset** [comment]
That should do the trick, thank you.

**Comment by dheckenberg** [comment]
Thanks John.

**Pull request merged**
