### PR TITLE
OTIO suggestions

### PR DESCRIPTION
**Pull request by meshula**
Suggestions from the OTIO team

Signed-off-by: Nick Porcino <nporcino@pixar.com>

### CODE REVIEW

**Comment by meshula** [comment]
Hi! Any tips on resolve the sign off check?

**Comment by lgritz** [comment]
I think your sign-off is not formatted correctly

**Comment by meshula** [comment]
Resolved! Thanks for looking!

**Comment by meshula** [comment]
mentor suggestions added!

**Pull request merged**
