### PR TITLE
Order TAC meeting agenda items properly, grouping short items under "General Updates"

### PR DESCRIPTION
**Pull request by jmertic**
@jfpanisset This should help fix the issues with agenda items.

### CODE REVIEW

**Comment by jmertic** [comment]
@jfpanisset Take a look at https://deploy-preview-607--aswf-tac.netlify.app/meetings/template and see if that helps make this work better

**Comment by jfpanisset** [comment]
Seems useful, thanks!

A small thing: I've been asked for a bit more granularity in the attendee list, in particular people who represent WGs and non-voting projects, so typically I've created:

* Non Voting Projects, Working Groups, Linux Foundation
* Other Attendees

So eventually would be great if that made it into the template

**Comment by jmertic** [comment]
Sure thing - take a look now and see if that is what you are after.

**Comment by jfpanisset** [comment]
Perfect!

**Pull request merged**
