### PR TITLE
Create 2023-01-10.md

### PR DESCRIPTION
**Pull request by jmertic**
They aren't as amazing as @jfpanisset notes, but should work.

### CODE REVIEW

**Review by jfpanisset — APPROVED** [review]
LGTM, once merged I'll add the PDF documents for raw2aces and ocio for previous presentation.

Going forward I'll make sure to try to get presentation documents for projects that want to have those included in meeting notes.

Thanks!

**Comment by jmertic** [comment]
Thanks @jfpanisset 

I might suggest we add them to the GH issue for the agenda item - so for OpenVDB lets add it to #480 . What do you think?

**Comment by jfpanisset** [comment]
Do you mean attaching the presentation PDF to the corresponding GH issue as well as adding it to the meeting notes that get committed to the tac repo?

**Comment by jmertic** [comment]
Hey - just attach to the GH issue and not the notes; you could then reference from the notes as needed. This will give us a better chronology of reviews and ways we can point other projects to past reviews as examples.On Jan 20, 2024, at 2:18 PM, Jean-Francois Panisset ***@***.***> wrote:﻿
Do you mean attaching the presentation PDF to the corresponding GH issue as well as adding it to the meeting notes that get committed to the tac repo?

**Pull request merged**
