### PR TITLE
Initial draft of Contribution Guidelines recommendations for projects hosted by ASWF

### PR DESCRIPTION
**Pull request by jmertic**
Please review and provide feedback and comments either inline or as a pull request. Also, please add any additional questions to the FAQ as PRs so we can capture. Thank you!

Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by jfpanisset** [comment]
- All seems good to me
- The CCLA (Corporate CLA) acronym is used without being first defined, its meaning can be inferred from the ccla_template.md linked document, but would be good to explicitly define it
- In the discussion about copyright notices and SPDX IDs, would it be useful to provide a sample empty source code file showing the desired header information?
- I had never used the DCO mechanism before until I tried to submit a change to the top level README.md file for the tac project, I found the process a bit confusing, in particular when submitting a pull request for a small change directly from the GitHub web UI rather than from git itself, I was unable to find where I was supposed to put the Signed-off-by comment. Perhaps a link to a tutorial on how to use DCO in the context of GitHub would be useful.

**Comment by jmertic** [comment]
@jfpanisset Great points! I've incorporated your suggestions now - can you review and let me know if that addresses your points?

**Comment by swallitsch** [comment]
It's looking really nice. While the additional clarity of the spdx and copyright notice are good, a simple example might illustrate the goal here more succinctly. In addition, it's possible that these two sections might work better combined (or it might be terrible).

``` python
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the BananaBoat Project.
```

Going above and beyond, it might be useful to include a sample `contributing.md` which ASWF projects could copy use directly to implement the ideal ASWF contributing workflow, as this document is more of a set of recommendations and FAQs, and projects would still have to translate it into their own `contributing.md` file.

**Comment by swallitsch** [comment]
Yup, that would do it.

Also, despite how much I love using BananaBoat in unittests, I realized this morning that it's technically a trademarked term so we should probably just use Foo in the example. Sorry :(

**Comment by jmertic** [comment]
No worries - will change now!

<https://calendly.com/jmertic>

**Comment by dheckenberg** [comment]
LGTM -- Thanks John, Everyone!

**Pull request merged**
