### PR TITLE
Update TAC representatives - 20210101

### PR DESCRIPTION
**Pull request by jmertic**
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by lgritz** [comment]
As a related FYI, the public web page on aswf.io is pretty outdated -- some old affiliations and titles, etc.

**Comment by jmertic** [comment]
Can you detail the updates needed? Just want to ensure I don't miss anything.

**Comment by lgritz** [comment]
I don't have a comprehensive list. Chris (affilliation), Daniel and Kimball (ASWF roles) for sure, and I'd recommend spot check the others that you changed in this PR.

**Comment by jmertic** [comment]
Fixed those

**Pull request merged**
