### PR TITLE
Create Project Success metrics

### PR DESCRIPTION
**Pull request by jmertic**

### CODE REVIEW

**Comment by mpgjon** [comment]
Open Source Project Success Metrics Framework

Objective: Craft a framework that outlines what a “successful” open source project looks like in objective (and perhaps some subjective?) ways, and what potential actions communities can take to increase their chances of being a successful project.  

If we’re speaking only about “metrics” then we should look to implement [CHAOSS.](https://github.com/chaoss/metrics) That project has just recently released their 1.0 of open source health metrics. 

It is also important for communities to be clear that “what is successful” for a project will change over time.  Projects naturally mature over time, and move to LTS releases where, depending on demand for the project, may mean less activity. 

State assumptions on what kind of project the founders want it to be.  

Sometimes, founders want to open source something just because they found it valuable and thought others could use it, and that’s the end of it.  Other times, founders want a project that can take the journey from first release/MVP to a mature product with many releases and new features added over the years.

This framework will assume the latter and for the sake of that assumption, we will work to lay out what a successful and healthy open source project looks like in today’s software development world.

Active founders (>1?)
Active maintainers (>1?)
Active contributors (>1?)

How to measure “active” without (or with?) something like CHAOSS implemented?

Healthy backlog of issues?  (>? How many issues already identified/approximating a product roadmap?)

Has the project made it to a 1.0 release?  

How many stars/forks (over time? Maybe per year?) (CHAOSS)

**Comment by mpgjon** [comment]
Another comment to add: 

Does a project include a clear onboarding/get involved process.  Often, this is as simple as flagging issues in Github as "Good First Issue" and giving some direction.

**Comment by jmertic** [comment]
@mpgjon Good stuff! Would you mind incorporating in [process/success_metrics.md](https://github.com/jmertic/aswf-tac/edit/master/process/success_metrics.md?pr=%2FAcademySoftwareFoundation%2Ftac%2Fpull%2F93)

**Comment by dheckenberg** [comment]
I'll make some time to discuss this in the TAC meeting.

**Comment by mpgjon** [comment]
Hi Dan, can you lmk what TAC meeting you would like to address this in, so
I can try to block out time with the day job?

Thanks!

Jon

**Comment by jmertic** [comment]
Hey @mpgjon - seeing what next steps are here. Wondering if you wanted to incorporate your suggestions into the file?

**Comment by jmertic** [comment]
Closing this - will re-open as a new PR

**Pull request closed without merging**
