### PR TITLE
Project lifecycle update - Archive stage

### PR DESCRIPTION
**Pull request by jmertic**
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by lgritz** [comment]
This kind of makes it seem like a project that hasn't had the need for changes for >6 months could be involuntarily put into a state where the only allowed changes are security issues (not even ordinary bug fixes).

I can imagine a project whose development is inactive for months or even years -- because it is 100% successful, has all the desired features and no important outstanding bugs -- but still need to accommodate the occasional bug found, or needing changes to support new compiler versions, etc.

I think the criteria for involuntary archival ought not to be frequency of commits, but rather status of use in the industry. If nobody is using it any more, then you archive it. If it's widely used but just doesn't happen to need any code changes, even for long periods of time, it should still be "adopted,"  even if it's "inactive." It may be that an adopted, but inactive, project no longer needs a standing meeting, a formal TSC beyond a sole administrator, or a voting seat on the TAC. But that doesn't necessarily mean it should be frozen without any changes allowed.

**Comment by jmertic** [comment]
Hey @lgritz - fair points. The language is meant to be vague because there can be a multitude of reasons why a project is archived, thus giving the TAC some latitude on the why. Generally, I see archiving as a realization by the project that the momentum has come to an end or the maintainers no longer wanting to do the work; I don't think I've ever seen a TAC force a project into archival against a project's will.

The intention of archiving is that there wouldn't be any active support from the part of the foundation until someone came forward to do that. I've never seen a project where there are people willing to do work be forced into archival...

**Comment by lgritz** [comment]
Perhaps it's adequate to just clarify that "insufficient activity" doesn't refer to the frequency of commits (which may be infrequent because they simply are not necessary), but rather refers to either inattention of any developers or apparent lack of users needing the project to be updated.

**Comment by jmertic** [comment]
Feel free to tweak the language with a PR. Agreed this should be spelled
out.

**Pull request merged**
