### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by jmertic**
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by jmertic** [comment]
@dheckenberg Can we add this to the next TAC meeting agenda?

**Comment by lgritz** [comment]
Do those individual codes of conduct have any substantive differences? Or do they all refer back to the LF COC and just differ in how they paraphrase/summarize?

TBH, I think it would be better for the TAC to make just a single recommendation for a COC document that can be dropped into any new project, not make people hunt through 5 projects and try to discern how they might differ. 

Those projects, too, if there are not substantial differences between what they aiming to do, should be encouraged to switch to a common document.

**Comment by jmertic** [comment]
I think if that's the direction the TAC wants to go, it's certainly an approach I see in other umbrella foundations so it does have precedent. 

I will say all but OpenTimelineIO either call out the LF one specifically or build upon it. OpenVDB as you see doesn't have one ( probably just should add one in that's a pointer to this doc ) and OSL has one in the docs to approve.

**Comment by lgritz** [comment]
OSL just copied verbatim either OpenEXR or OCIO (I honestly forget which) and called it a day. Whichever it is, it is actually the LF one, with a bit of paraphrasing of key points for people too lazy to follow the link and read the whole thing.

**Comment by jminor** [comment]
FYI, OpenTimelineIO used the default Code of Conduct template recommended by GitHub, which comes from here: https://www.contributor-covenant.org/. We can review the differences between that and the LF one. I will say that it took a fair number of meetings internally to align people on the value of having a code of conduct at all, let alone which one to pick, so changing this may take some time.

---
Joshua Minor (he-him)
Pixar Studio Tools Story/Editorial/VR Previs Tech Lead
joshm@pixar.com

**Comment by dheckenberg** [comment]
I'll add to TAC meeting agenda.

**Comment by dheckenberg** [comment]
I've attempted to update taking PR comments and TAC discussion on board.

@jmertic @lgritz @jminor is this acceptable?

ps Does anyone know an elegant way to fix the lack of DCO on a PR-edit commit from the Github UI?

**Comment by jmertic** [comment]
@dheckenberg Here's what I've used and works really well...

    Chrome - https://chrome.google.com/webstore/detail/dco-github-ui/onhgmjhnaeipfgacbglaphlmllkpoijo
    Firefox - https://addons.mozilla.org/en-US/firefox/addon/scott-rigby/?src=search

Let me do a PR and add it to the contributing doc :-)

**Comment by dheckenberg** [comment]
Thanks @jmertic !  I haven't used the UI edit process before and forgot to append the DCO manually.  Those tools look handy.  I couldn't see an easy way to fix the "broken" commit which presumably would require a force-push to your fork.  Feel free to remove the commit and I can resubmit with DCO.

**Comment by jmertic** [comment]
I think this is more of a GitHub issue than anything. I'm tempted to just mark the DCO to pass and then squash merging this together to get rid of the cruft commit messages that the DCO bot is choking on - ok by you @dheckenberg ?

**Comment by lgritz** [comment]
LGTM. I also just ended up making the OSL CoC file just simply say we adhered to the LF one and give the link to it.

**Comment by jminor** [comment]
@dheckenberg yes, this looks fine to me. OTIO TSC will discuss switching to the LF CoC to conform to the others. If/when we do that, then we can simplify this.

**Pull request merged**
